<PageLayoutWidget>:
    #设置边界
    border: '100'
    #设置翻页动画及其持续时间
    anim_kwargs: {'d':10,'t': 'linear'}
    #设置默认第几页为当前页
    page: 2
    # 设置翻页灵敏度
    swipe_threshold: 0.8

    Button:
        text:'Page0'
        background_color: 0.3,0.3,0.3,1

    Button:
        text:'Page1'
        background_color: 0.9,0.3,0.3,1

    Button:
        text:'Page2'
        background_color: 0.3,0.9,0.3,1

    Button:
        text:'Page3'
        background_color: 0.3,0.3,0.9,1

